"""Generate Markdown daily report with tree-aware sections."""

from __future__ import annotations

import logging
import sqlite3
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

from .config import Settings, Topic
from .collector import RawPaper
from .filter import RelevantPaper
from .storage import (
    get_analyzed_papers, get_links_for_paper,
)

logger = logging.getLogger(__name__)

MAX_ABSTRACT_LENGTH = 500


def _truncate(text: str, max_len: int = MAX_ABSTRACT_LENGTH) -> str:
    if len(text) <= max_len:
        return text
    return text[:max_len].rsplit(" ", 1)[0] + "..."


def _first_author(paper: RawPaper) -> str:
    return paper.authors[0] if paper.authors else "Unknown"


def _first_author_from_stored(paper: StoredPaper) -> str:
    authors = paper.authors.split("\n") if paper.authors else []
    return authors[0] if authors else "Unknown"


def _author_count(paper: RawPaper) -> int:
    return len(paper.authors)


def _author_count_from_stored(paper: StoredPaper) -> int:
    if not paper.authors:
        return 0
    return len(paper.authors.split("\n"))


def generate_report(
    relevant: list[RelevantPaper],
    total_scanned: int,
    topics: list[Topic],
    all_categories: list[str],
    settings: Settings,
) -> Path:
    """Generate a Markdown report file and return its path (legacy format)."""
    output_dir = Path(settings.report_output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filepath = output_dir / f"{today}.md"

    score_dist = Counter(r.score for r in relevant)
    topic_dist = Counter(r.matched_topic for r in relevant)
    cat_dist = Counter(
        cat for r in relevant for cat in r.paper.categories if cat in set(all_categories)
    )

    lines: list[str] = []

    lines.append(f"# ArXistant Daily Report — {today}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Papers scanned:** {total_scanned}")
    lines.append(f"- **Relevant papers:** {len(relevant)}")
    lines.append(f"- **Categories monitored:** {', '.join(sorted(set(all_categories)))}")
    lines.append(f"- **Topics:** {', '.join(t.name for t in topics)}")
    lines.append("")

    if topic_dist:
        lines.append("### Relevance by topic")
        lines.append("")
        for topic_name, count in topic_dist.most_common():
            lines.append(f"- **{topic_name}**: {count} papers")
        lines.append("")

    if cat_dist:
        lines.append("### Relevant papers by category")
        lines.append("")
        for cat, count in cat_dist.most_common():
            lines.append(f"- `{cat}`: {count} papers")
        lines.append("")

    if score_dist:
        lines.append("### Score distribution")
        lines.append("")
        for score in sorted(score_dist.keys(), reverse=True):
            lines.append(f"- Score {score}: {score_dist[score]} papers")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Relevant Papers")
    lines.append("")

    for i, rp in enumerate(relevant, 1):
        p = rp.paper
        first = _first_author(p)
        n_authors = _author_count(p)
        author_str = f"{first} et al." if n_authors > 1 else first

        lines.append(f"### {i}. {p.title}")
        lines.append("")
        lines.append(f"- **Authors:** {author_str} ({n_authors} total)")
        lines.append(f"- **Score:** {rp.score}/5")
        lines.append(f"- **Matched topic:** {rp.matched_topic}")
        lines.append(f"- **Reason:** {rp.reason}")
        lines.append(f"- **arXiv:** [{p.arxiv_id}]({p.entry_url})")
        lines.append(f"- **PDF:** [Download]({p.pdf_url})")
        lines.append(f"- **Categories:** {', '.join(p.categories)}")
        lines.append(f"- **Published:** {p.published.strftime('%Y-%m-%d')}")
        lines.append("")
        lines.append(f"> {_truncate(p.abstract)}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by ArXistant on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")

    report_text = "\n".join(lines)
    filepath.write_text(report_text, encoding="utf-8")
    logger.info("Report saved to %s (%d papers, %d lines)", filepath, len(relevant), len(lines))
    return filepath


def generate_tree_report(
    conn: sqlite3.Connection,
    total_scanned: int,
    topics: list[Topic],
    all_categories: list[str],
    settings: Settings,
) -> Path:
    """Generate a tree-aware Markdown report and return its path.

    Reads all analyzed papers and their tree links from the database.
    """
    from .storage import (
        get_all_tree_nodes, count_papers, get_pending_candidates,
        get_tree_node_by_name,
    )

    output_dir = Path(settings.report_output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filepath = output_dir / f"{today}.md"

    # Get analyzed papers from DB (sorted by quality desc)
    papers = get_analyzed_papers(conn)
    quality_dist = Counter(p.quality_score for p in papers if p.quality_score)

    # Build paper→links mapping from DB
    paper_links: dict[str, list[dict]] = {}
    for p in papers:
        links = get_links_for_paper(conn, p.arxiv_id)
        if links:
            paper_links[p.arxiv_id] = links

    # Build tree node → papers mapping
    node_papers: dict[int, list[dict]] = defaultdict(list)
    for p in papers:
        links = paper_links.get(p.arxiv_id, [])
        for link in links:
            node_papers[link["tree_node_id"]].append({
                "paper": p,
                "relevance_score": link["relevance_score"],
                "relevance_reason": link["relevance_reason"],
            })

    # Get tree structure for report
    all_nodes = get_all_tree_nodes(conn)
    node_map: dict[int, dict] = {n.id: {"node": n, "children": []} for n in all_nodes}
    roots: list[int] = []
    for n in all_nodes:
        if n.parent_id is None:
            roots.append(n.id)
        elif n.parent_id in node_map:
            node_map[n.parent_id]["children"].append(n.id)

    # Get pending candidates
    candidates = get_pending_candidates(conn)

    # Build report
    lines: list[str] = []

    lines.append(f"# ArXistant Daily Report — {today}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total papers in database:** {count_papers(conn)}")
    lines.append(f"- **Papers analyzed:** {len(papers)}")
    lines.append(f"- **Papers scanned this run:** {total_scanned}")
    lines.append(f"- **Categories monitored:** {', '.join(sorted(set(all_categories)))}")
    lines.append(f"- **Tree nodes:** {len(all_nodes)}")
    lines.append("")

    # Quality distribution
    if quality_dist:
        lines.append("### Quality distribution")
        lines.append("")
        for score in sorted(quality_dist.keys(), reverse=True):
            lines.append(f"- Quality {score}: {quality_dist[score]} papers")
        lines.append("")

    lines.append("---")
    lines.append("")

    # Papers by tree node
    lines.append("## Papers by Knowledge Tree")
    lines.append("")

    def _write_node(node_id: int, heading_level: int, prefix: str) -> None:
        nd = node_map[node_id]["node"]
        child_papers = node_papers.get(node_id, [])
        lines.append(f"{'#' * heading_level} {nd.name}")
        lines.append("")
        if nd.description:
            lines.append(f"*{nd.description}*")
            lines.append("")

        if child_papers:
            child_papers.sort(key=lambda x: x["relevance_score"], reverse=True)
            for cp in child_papers:
                p = cp["paper"]
                rel = cp["relevance_score"]
                rel_reason = cp["relevance_reason"]
                first = _first_author_from_stored(p)
                n_authors = _author_count_from_stored(p)
                author_str = f"{first} et al." if n_authors > 1 else first
                qs = p.quality_score or 0

                lines.append(f"#### {p.title}")
                lines.append("")
                lines.append(f"- **Authors:** {author_str} ({n_authors} total)")
                lines.append(f"- **Quality:** {qs}/5")
                lines.append(f"- **Relevance to this topic:** {rel}/5")
                if rel_reason:
                    lines.append(f"- **Relevance reason:** {rel_reason}")
                lines.append(f"- **arXiv:** [{p.arxiv_id}]({p.entry_url})")
                lines.append(f"- **PDF:** [Download]({p.pdf_url})")
                lines.append("")

        for child_id in node_map[node_id]["children"]:
            _write_node(child_id, heading_level + 1, prefix + "  ")

    for root_id in roots:
        _write_node(root_id, 3, "")

    # Papers with no tree links
    all_linked_ids = set()
    for link_list in paper_links.values():
        for link in link_list:
            all_linked_ids.add(link["paper_id"])
    unlinked = [p for p in papers if p.arxiv_id not in all_linked_ids and p.quality_score and p.quality_score >= 3]

    if unlinked:
        lines.append("---")
        lines.append("")
        lines.append(f"## High-Quality Unlinked Papers ({len(unlinked)})")
        lines.append("")
        for p in unlinked[:10]:  # limit to 10
            first = _first_author_from_stored(p)
            n_authors = _author_count_from_stored(p)
            author_str = f"{first} et al." if n_authors > 1 else first
            lines.append(f"### {p.title}")
            lines.append("")
            lines.append(f"- **Authors:** {author_str} ({n_authors} total)")
            lines.append(f"- **Quality:** {p.quality_score}/5")
            lines.append(f"- **arXiv:** [{p.arxiv_id}]({p.entry_url})")
            lines.append("")

    # Candidate proposals
    if candidates:
        lines.append("---")
        lines.append("")
        lines.append(f"## New Concept Proposals ({len(candidates)} pending)")
        lines.append("")
        lines.append("*Edit `data/candidates.yaml` to confirm or reject these proposals.*")
        lines.append("")
        for c in candidates:
            parent_name = c.get("parent_name", "Unknown")
            lines.append(f"- **{c['name']}** (child of *{parent_name}*)")
            if c["description"]:
                lines.append(f"  - {c['description']}")
            papers_str = c.get("source_paper_ids") or "none"
            lines.append(f"  - Suggested by papers: {papers_str}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by ArXistant on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")

    report_text = "\n".join(lines)
    filepath.write_text(report_text, encoding="utf-8")
    logger.info("Tree report saved to %s (%d analyzed papers)", filepath, len(papers))
    return filepath
