"""Generate Markdown daily report for relevant papers."""

from __future__ import annotations

import logging
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from .config import Settings, Topic
from .collector import RawPaper
from .filter import RelevantPaper

logger = logging.getLogger(__name__)

MAX_ABSTRACT_LENGTH = 500


def _truncate(text: str, max_len: int = MAX_ABSTRACT_LENGTH) -> str:
    if len(text) <= max_len:
        return text
    return text[:max_len].rsplit(" ", 1)[0] + "..."


def _first_author(paper: RawPaper) -> str:
    return paper.authors[0] if paper.authors else "Unknown"


def _author_count(paper: RawPaper) -> int:
    return len(paper.authors)


def generate_report(
    relevant: list[RelevantPaper],
    total_scanned: int,
    topics: list[Topic],
    all_categories: list[str],
    settings: Settings,
) -> Path:
    """Generate a Markdown report file and return its path."""
    output_dir = Path(settings.report_output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filepath = output_dir / f"{today}.md"

    # Build summary stats
    score_dist = Counter(r.score for r in relevant)
    topic_dist = Counter(r.matched_topic for r in relevant)
    cat_dist = Counter(
        cat for r in relevant for cat in r.paper.categories if cat in set(all_categories)
    )

    lines: list[str] = []

    # Header
    lines.append(f"# ArXistant Daily Report — {today}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Papers scanned:** {total_scanned}")
    lines.append(f"- **Relevant papers:** {len(relevant)}")
    lines.append(f"- **Categories monitored:** {', '.join(sorted(set(all_categories)))}")
    lines.append(f"- **Topics:** {', '.join(t.name for t in topics)}")
    lines.append("")

    if topic_dist:
        lines.append("### Relevance by topic")
        lines.append("")
        for topic_name, count in topic_dist.most_common():
            lines.append(f"- **{topic_name}**: {count} papers")
        lines.append("")

    if cat_dist:
        lines.append("### Relevant papers by category")
        lines.append("")
        for cat, count in cat_dist.most_common():
            lines.append(f"- `{cat}`: {count} papers")
        lines.append("")

    if score_dist:
        lines.append("### Score distribution")
        lines.append("")
        for score in sorted(score_dist.keys(), reverse=True):
            lines.append(f"- Score {score}: {score_dist[score]} papers")
        lines.append("")

    # Paper list
    lines.append("---")
    lines.append("")
    lines.append("## Relevant Papers")
    lines.append("")

    for i, rp in enumerate(relevant, 1):
        p = rp.paper
        first = _first_author(p)
        n_authors = _author_count(p)
        author_str = f"{first} et al." if n_authors > 1 else first

        lines.append(f"### {i}. {p.title}")
        lines.append("")
        lines.append(f"- **Authors:** {author_str} ({n_authors} total)")
        lines.append(f"- **Score:** {rp.score}/5")
        lines.append(f"- **Matched topic:** {rp.matched_topic}")
        lines.append(f"- **Reason:** {rp.reason}")
        lines.append(f"- **arXiv:** [{p.arxiv_id}]({p.entry_url})")
        lines.append(f"- **PDF:** [Download]({p.pdf_url})")
        lines.append(f"- **Categories:** {', '.join(p.categories)}")
        lines.append(f"- **Published:** {p.published.strftime('%Y-%m-%d')}")
        lines.append("")
        lines.append(f"> {_truncate(p.abstract)}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by ArXistant on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")

    report_text = "\n".join(lines)
    filepath.write_text(report_text, encoding="utf-8")
    logger.info("Report saved to %s (%d papers, %d lines)", filepath, len(relevant), len(lines))
    return filepath
